name: get-upcoming-match
on:
    workflow_dispatch:
    push:
        branches:
            main
        paths:
            get-upcoming-matches/**

jobs: 
    update-lambda:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-2

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: latest
                cache: npm

            - name: Remove aws module
              run: rm -r aws
            
            - name: Install dependencies
              run: npm i

            - name: Zip code and dependencies
              run: zip -r function .
            
            - name: Sync S3 bucket 
              run: aws s3 cp ./function.zip s3://ticket-tracker-lambda-code-bucket-get-upcoming-matches
            
            - name: Update lambda function
              run: aws lambda update-function-code --function-name get-upcoming-matches-ticket-tracker --s3-bucket ticket-tracker-lambda-code-bucket-get-upcoming-matches --s3-key function.zip 